name: miko
description: "Miko — aplikasi baca komik (manga, manhua, manhwa) dengan antarmuka bergaya iOS."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/miko_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A1830"
  adaptive_icon_foreground: "assets/icon/miko_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
